### PR TITLE
Add newline between headers

### LINKED ISSUE #7: Headers are merged when converting from view to markdown
When placing two headers in the view next to each other:
```html
<h1>header</h1><h1>header</h1>
```

They are converted incorrectly to:
```markdown
# header# header
```

It should be:
```markdown
# header
# header
```

### LINKED ISSUE #2307: Headers are merged when converting from view to markdown
When placing two headers in the view next to each other:

``` html
<h1>header</h1><h1>header</h1>
```

They are converted incorrectly to:

``` markdown
# header# header
```

It should be:

``` markdown
# header
# header
```

### PR DESCRIPTION
**Pull request by szymonkups**
FIxes ckeditor/ckeditor5#2307.

### CODE REVIEW

**Comment by Reinmar** [comment]
Wait... what? Is `src/lib/converters/*` our code? I thought it's an external library (cause it's in `lib` :P).

**Comment by szymonkups** [comment]
It is code based based on a standard library converters, just aligned to match our needs, the same is with `src/lib/marked/renderer.js`. Both libraries allows us to override their own methods, but sometimes it was just a matter of removing newline or adding it; or small format change. Rest of the code stayed the same, so I left them in `lib/` directory. But now when I think of it - wasn't a good idea :sweat_smile:

**Comment by Reinmar** [comment]
I added one test – please check if it's not duplicated somewhere.

**Comment by Reinmar** [comment]
I reported a separate ticket for the code in `lib/`: https://github.com/ckeditor/ckeditor5-markdown-gfm/issues/9.

**Pull request merged**
